package com.rrhh.modelo.enums;

public enum Permiso {
    VER_EMPLEADOS,
    GESTIONAR_EMPLEADOS,
    VER_DEPARTAMENTOS,
    GESTIONAR_DEPARTAMENTOS,
    VER_NOMINA_PROPIA,
    VER_NOMINA_TODOS,
    GESTIONAR_NOMINA,
    VER_SOLICITUDES_PROPIAS,
    CREAR_SOLICITUDES,
    APROBAR_SOLICITUDES,
    VER_DASHBOARD,
    GENERAR_REPORTES
}
